config/routes.rb
Gradr::Application.routes.draw do
  root 'users#request_invite'
  post '/' => 'users#request_invite', as: 'invite_request'
  get 'login/:slug/:link_hash' => 'users#login'
  get 'logout' => 'users#logout', as: 'logout'
  get 'dashboard' => 'users#dashboard', as: 'dashboard'
  get 'stats/for/:gradee_slug/by/:grader_slug' => 'users#stats', as: 'user_stats'
  get 'scorecard' => 'scorecards#edit', as: 'scorecard_editor'
  post 'scorecard/:id/invite-gradee' => 'scorecards#invite_gradee'
  post 'scorecard/:id/save' => 'scorecards#save'
  post 'criteria/create' => 'criteria#create', as: 'criteria_create'
  post 'criteria/remove' => 'criteria#remove', as: 'criteria_remove'

  

end

app/models/user.rb
require 'bcrypt'

class User < ActiveRecord::Base
  extend FriendlyId
  include GradeeStats
  friendly_id :slug_candidates, use: :slugged
  validates :email, format: { with: /\A[A-Za-z0-9._%+-]+@[A-Za-z0-9.-]+\.[A-Za-z]+\z/, message: 'Must be a valid email address'}
  has_and_belongs_to_many :criteria, join_table: "user_criteria"
  has_many :grader_scorecards, class_name: 'Scorecard', foreign_key: 'grader_id'
  has_many :gradee_scorecards, class_name: 'Scorecard', foreign_key: 'gradee_id'
  has_many :graders, through: :gradee_scorecards
  has_many :gradees, through: :grader_scorecards

  def slug_candidates
    [:email]
  end

  attr_accessible :email

  def random_string
    Time.new.to_f.to_s.gsub(/\./, '').concat((0...10).map{ ('a'..'z').to_a[rand(26)] }.join).split("").shuffle.join.concat(Time.new.to_f.to_s.gsub(/\./, ''))
  end

  def encrypt(string)
    Digest::SHA1.hexdigest string.to_s
  end

  def update_password
    self.link_hash = self.random_string
    self.salt = self.random_string
    self.password = BCrypt::Password.create("#{self.link_hash}#{self.salt}")
    self.save
  end

  def invite(email, msg_params={:type => 'login_request'})
    user = User.find_by_email(email.strip) || User.new({:email => email.strip})
    user.update_password
    msg_params[:user] = user
    UserMailer.invite(msg_params).deliver
    user
  end

  def check_link_hash(hash)
    match = BCrypt::Password.new(self.password) == "#{hash}#{self.salt}"
    self.update_password
    match
  end

  def gravatar_url
    hash = Digest::MD5.hexdigest(self.email.downcase.strip)
    "http://www.gravatar.com/avatar/#{hash}"
  end
    
end

app/controllers/users_controller.rb
class UsersController < ApplicationController
  def login
    @user = User.friendly.find params[:slug] 
    if !@user.check_link_hash params[:link_hash]
      return not_found
    end
    self.sign_in @user
    redirect_to dashboard_url
  end

  def logout
    self.sign_out self.current_user
    redirect_to '/'
  end

  def request_invite
    if signed_in?
      redirect_to dashboard_url and return
    end
    @user = params[:user] ? User.new.invite(params[:user][:email]) : User.new
    respond_to do |f|
      f.html { render :layout => false }
    end
  end

  def dashboard
   @graders = current_user.graders.paginate(:page => params[:graders_page]).uniq
   @gradees = current_user.gradees.paginate(:page => params[:gradees_page]).uniq
  end

  def stats
    @grader = User.friendly.find params[:grader_slug]
    @gradee = User.friendly.find params[:gradee_slug]
    if current_user.id != @grader.id and current_user.id != @gradee.id
      return not_found
    end
    @title = current_user.id == @grader.id ? "Stats for gradee #{@gradee.email}" : "Stats from grader #{@grader.email}"
    @scorecards = Scorecard.where('updated_at > ? and grader_id = ? and gradee_id = ?', 2.months.ago, @grader.id, @gradee.id).order('updated_at ASC')
                            .preload(:scores)
    @scorecards_data = {}
    @scorecards.each do |s|
      @scorecards_data[s.id] = {}
      @scorecards_data[s.id]['url'] = s.url
      @scorecards_data[s.id]['date'] = s.updated_at
      @scorecards_data[s.id]['scores'] = {}
      @grader.criteria.each {|c| @scorecards_data[s.id]['scores'][c.name] = c.score_for_scorecard(s).score}
    end
    puts @scorecards_data
  end
end

app/helpers/users_helper.rb
module UsersHelper
end

app/views/users/dashboard.html.erb
<%= provide :title, 'Dashboard' %>
<%= content_for :scripts do %>
  <script type="text/javascript">
    $(document).ready(function(){
        $('.recent-activity-chart').each(function(){
          $(this).sparkline($(this).data('activity'), {
              type: 'bar',
		chartRangeMin: 0,
		chartRangeMax: 10});
        });
    });
  </script>
<% end %>
<% if @gradees.length > 0 %>
<div class="portlet box blue">
  <div class="portlet-title">
    Your Gradees
  </div>
  <div class="portlet-body">
    <div class="table-responsive">
      <table class="table">
        <thead>
          <tr>
            <th>Gradee</th>
            <th>Recent Activity (avg score)</th>
            <th>Recent Overall Average</th>
            <th></th>
          </tr>
        </thead>
        <tbody>
          <% @gradees.each do |gradee| %>
          <tr>
            <td>
             <%= gradee.email %>
            </td>
            <td>
              <div class="recent-activity-chart" data-activity=<%= gradee.averages_by_grader_since(current_user.id, 3.weeks.ago).to_json %>></div>
            </td>
            <td>
              <%= gradee.average_by_grader_since current_user.id, 3.weeks.ago %>
            </td>
            <td>
              <%= link_to 'Details', {controller: 'users', action: 'stats', gradee_slug: gradee.slug, grader_slug: current_user.slug} %>
            </td>
          </tr>
          <% end %>
        </tbody>
      </table>
    </div>
  </div>
</div>
<% end %>
<% if @graders.length > 0 %>
<div class="portlet box blue">
  <div class="portlet-title">
    Your Graders 
  </div>
  <div class="portlet-body">
    <div class="table-responsive">
      <table class="table">
        <thead>
          <tr>
            <th>Grader</th>
            <th>Recent Activity (avg score)</th>
            <th>Recent Overall Average</th>
            <th></th>
          </tr>
        </thead>
        <tbody>
          <% @graders.uniq.each do |grader| %>
          <tr>
            <td>
             <%= grader.email %>
            </td>
            <td>
              <div class="recent-activity-chart" data-activity=<%= current_user.averages_by_grader_since(grader.id, 3.weeks.ago).to_json %>></div>
            </td>
            <td>
              <%= current_user.average_by_grader_since grader.id, 3.weeks.ago %>
            </td>
            <td>
              <%= link_to 'Details', {controller: 'users', action: 'stats', gradee_slug: current_user.slug, grader_slug: grader.slug} %>
            </td>
          </tr>
          <% end %>
        </tbody>
        <%= will_paginate @graders %>
      </table>
    </div>
  </div>
</div>
<% end %>
<div>
  <div class="pull-right">
    <a class="btn blue btn-sm" href="javascript:(function(){var i=document.getElementById('gradr-iframe')||document.createElement('iframe'),u=window.location.href;i.style.position='fixed';i.style.top='50px';i.style.right='10px';i.style.width='200px';i.style.height='800px';i.id='gradr-iframe';i.src='//<%= ENV['APP_URL'] %>/scorecard/?url='+u;if(!document.getElementById('gradr-iframe'))document.body.appendChild(i);}());">
      GRADR
    </a>
    <span class="label label-info"><i class="icon-arrow-left"></i>Click and drag to your bookmarks bar to grade any page on the web</span>
  </div><br />
  <hr />
</div>

app/views/users/login.html.erb
<h1>Users#login</h1>
<p>Find me in app/views/users/login.html.erb</p>

app/views/users/request_invite.html.erb
<!DOCTYPE html>
<!-- 
Template Name: Metronic - Responsive Admin Dashboard Template build with Twitter Bootstrap 3.0
Version: 1.5.2
Author: KeenThemes
Website: http://www.keenthemes.com/
Purchase: http://themeforest.net/item/metronic-responsive-admin-dashboard-template/4021469?ref=keenthemes
-->
<!--[if IE 8]> <html lang="en" class="ie8 no-js"> <![endif]-->
<!--[if IE 9]> <html lang="en" class="ie9 no-js"> <![endif]-->
<!--[if !IE]><!--> <html lang="en" class="no-js"> <!--<![endif]-->
<!-- BEGIN HEAD -->
<head>
   <meta charset="utf-8" />
   <title>Gradr | Log in</title>
   <meta http-equiv="X-UA-Compatible" content="IE=edge">
   <meta content="width=device-width, initial-scale=1.0" name="viewport" />
   <meta content="" name="description" />
   <meta content="" name="author" />
   <meta name="MobileOptimized" content="320">
   <!-- BEGIN GLOBAL MANDATORY STYLES -->          
   <link href="/assets/plugins/font-awesome/css/font-awesome.min.css" rel="stylesheet" type="text/css"/>
   <link href="/assets/plugins/bootstrap/css/bootstrap.min.css" rel="stylesheet" type="text/css"/>
   <link href="/assets/plugins/uniform/css/uniform.default.css" rel="stylesheet" type="text/css"/>
   <!-- END GLOBAL MANDATORY STYLES -->
   <!-- BEGIN PAGE LEVEL STYLES --> 
   <link rel="stylesheet" type="text/css" href="/assets/plugins/select2/select2_metro.css" />
   <!-- END PAGE LEVEL SCRIPTS -->
   <!-- BEGIN THEME STYLES --> 
   <link href="/assets/css/style-metronic.css" rel="stylesheet" type="text/css"/>
   <link href="/assets/css/style.css" rel="stylesheet" type="text/css"/>
   <link href="/assets/css/style-responsive.css" rel="stylesheet" type="text/css"/>
   <link href="/assets/css/plugins.css" rel="stylesheet" type="text/css"/>
   <link href="/assets/css/themes/default.css" rel="stylesheet" type="text/css" id="style_color"/>
   <link href="/assets/css/pages/login-soft.css" rel="stylesheet" type="text/css"/>
   <link href="/assets/css/custom.css" rel="stylesheet" type="text/css"/>
   <!-- END THEME STYLES -->
   <link rel="shortcut icon" href="/favicon.ico" />
   <link href="/assets/plugins/bootstrap-toastr/toastr.min.css" rel="stylesheet" type="text/css" />
</head>
<!-- END HEAD -->
<!-- BEGIN BODY -->
<body class="login">
   <!-- BEGIN LOGO -->
   <div class="logo">
      <h3>GRADR</h3>
   </div>
   <!-- END LOGO -->
   <!-- BEGIN LOGIN -->
   <div class="content">
      <!-- BEGIN LOGIN FORM -->
      <%= form_for(:user, :url => invite_request_url,
                          :html => { :class =>  'login-form'}) do |f| %>
         <h3 class="form-title">Enter your email to login</h3>
         <div class="form-group">
            <!--ie8, ie9 does not support html5 placeholder, so we just show field title for that-->
            <label class="control-label visible-ie8 visible-ie9">Email</label>
            <div class="input-icon">
               <i class="icon-user"></i>
                  <%= f.text_field :email, :placeholder => 'Email Address', 
                              :value => '', :class => 'form-control' %>
            </div>
         </div>
         <div class="form-actions">
              <%= button_tag type: 'submit', class: 'btn blue pull-right' do %>
              Send login link <i class='m-icon-swapright m-icon-white'></i> 
              <% end %>
         </div>
      <% end %>
      <!-- END LOGIN FORM -->        
   </div>
   <!-- END LOGIN -->
   <!-- BEGIN COPYRIGHT -->
   <div class="copyright">
      2013 &copy; GRADR
   </div>
   <!-- END COPYRIGHT -->
   <!-- BEGIN JAVASCRIPTS(Load javascripts at bottom, this will reduce page load time) -->
   <!-- BEGIN CORE PLUGINS -->   
   <!--[if lt IE 9]>
   <script src="/assets/plugins/respond.min.js"></script>
   <script src="/assets/plugins/excanvas.min.js"></script> 
   <![endif]-->   
   <script src="/assets/plugins/jquery-1.10.2.min.js" type="text/javascript"></script>
   <script src="/assets/plugins/jquery-migrate-1.2.1.min.js" type="text/javascript"></script>
   <script src="/assets/plugins/bootstrap/js/bootstrap.min.js" type="text/javascript"></script>
   <script src="/assets/plugins/bootstrap-hover-dropdown/twitter-bootstrap-hover-dropdown.min.js" type="text/javascript" ></script>
   <script src="/assets/plugins/jquery-slimscroll/jquery.slimscroll.min.js" type="text/javascript"></script>
   <script src="/assets/plugins/jquery.blockui.min.js" type="text/javascript"></script>  
   <script src="/assets/plugins/jquery.cookie.min.js" type="text/javascript"></script>
   <script src="/assets/plugins/uniform/jquery.uniform.min.js" type="text/javascript" ></script>
   <!-- END CORE PLUGINS -->
   <!-- BEGIN PAGE LEVEL PLUGINS -->
   <script src="/assets/plugins/jquery-validation/dist/jquery.validate.min.js" type="text/javascript"></script>
   <script src="/assets/plugins/backstretch/jquery.backstretch.min.js" type="text/javascript"></script>
   <script type="text/javascript" src="/assets/plugins/select2/select2.min.js"></script>
   <!-- END PAGE LEVEL PLUGINS -->
   <!-- BEGIN PAGE LEVEL SCRIPTS -->
   <script src="/assets/scripts/app.js" type="text/javascript"></script>
   <script src="/assets/scripts/login-soft.js" type="text/javascript"></script>      
   <!-- END PAGE LEVEL SCRIPTS --> 
   <script>
      jQuery(document).ready(function() {     
        App.init();
        Login.init();
      });
   </script>
   <script src="/assets/plugins/bootstrap-toastr/toastr.min.js" type="text/javascript"></script>
    <script type="text/javascript">
      toastr.options = {positionClass: 'toast-top-center'};
    </script>
   <% if @user.errors.any? %>
    <script type="text/javascript">
      jQuery(document).ready(function() {
         <% @user.errors.full_messages.each do |msg| %>
           toastr.error("<%= msg %>", "");
         <% end %>
      });
     </script>
    <% elsif @user.id %>
    <script type="text/javascript">
        toastr.success("We've sent a login link to <%= @user.email %>", "");
    </script>
    <% end %>

   <!-- END JAVASCRIPTS -->
</body>
<!-- END BODY -->
</html>

app/views/users/stats.html.erb
<% provide :title, sanitize(@title) %>
<% content_for :styles do %>
<style>
ul.row{
padding-left:0px;
}
</style>
<% end %>
<% content_for :scripts do %>
  <script type="text/javascript" src="//cdnjs.cloudflare.com/ajax/libs/highcharts/3.0.2/highcharts.js"></script>
	<script type="text/template" id="chart_template">
			<li class="col-md-4">
				<div class="portlet solid blue">
					<div class="portlet-title">
						<div class="caption">
							{{= criteriumName }}
						</div>
            <div class="actions">
              <span class="number">Average: {{= criteriumAverage}}</span> 
            </div>
					</div>
					<div class="portlet-body" style="width:100%;height:100px;" id="{{= criterium }}-criterium">
					</div>
				</div>
			</li>
	</script>
  <script type="text/javascript">
    (function($, exports, undefined){
      exports.GradrStats = function(){
        var self = this;
        self.rawData = $.parseJSON($('#stats_json').text());
        self.allScores = _.flatten(_.map(_.pluck(self.rawData, 'scores'), function(o){return _.values(o);}));
        self.overAllAverage = (_.reduce(self.allScores, function(memo, num){ return memo+num; }, 0) / self.allScores.length).toFixed(2);
				self.criteria = _.keys(self.rawData[_.first(_.keys(self.rawData))].scores);
				self.criteriaSeries = function(){
					var series = {};
					_.each(self.criteria, function(criterium, id){
						series[id] = _.map(self.rawData, function(scorecard){
							return {x: new Date(scorecard.date).getTime(), y: scorecard.scores[criterium], url: scorecard.url};
						});
					});	
					return series;
				};
        self.averageForCriterium = function(criteriumIndex){
           var scores = _.pluck(self.criteriaSeries()[criteriumIndex], 'y');
           return (_.reduce(scores, function(memo, num){ return memo+num; }, 0) / scores.length).toFixed(2);
        };
      }; 

			_.templateSettings = {
					interpolate: /\{\{\=(.+?)\}\}/g,
					evaluate: /\{\{(.+?)\}\}/g
			};
			var g = new GradrStats();
			var markup = '', template = $('#chart_template').html();
			_.each(g.criteriaSeries(), function(series, criterium){
				markup += _.template(template, {criterium: criterium, criteriumName: g.criteria[criterium],
                                          criteriumAverage: g.averageForCriterium(criterium)});
			});
			$('#series-charts').html(markup);
			_.each(g.criteriaSeries(), function(series, criterium){
					$('#'+criterium+'-criterium').sparkline(_.pluck(series, 'y'), 
								{type: 'bar', width:'100%', height:'100px', barColor: '#eaedf2',
								chartRangeMin:0, chartRangeMax:10, barWidth: 3});
			});
      var baseChartOptions = {
            chart:{type: 'spline', spacingTop:44}, 
            xAxis:{type: 'datetime'},
             yAxis:{title:{text:"Score"}, min:0, max:10},
            tooltip:{xDateFormat: '%m/%d/%Y', useHTML: true, 
            formatter: function(){ return '<a href="'+this.point.url+'" target="_blank">'
                                    +Highcharts.dateFormat('%m/%d/%Y %I:%M %P', this.point.x)
                                    +'<br />'+this.series.name+': '+this.point.y+'<br /></a>'}}};
      $("#all-criteria-chart").highcharts(
          $.extend({}, baseChartOptions, {title: "All scores",
          series: _.map(g.criteriaSeries(), 
              function(series, criterium){return {name: g.criteria[criterium], data: series};})}));
       $('#overall-average').text(g.overAllAverage);
    }(jQuery, window));
  </script>
<% end %>
<div class="hidden" id="stats_json">
  <%= @scorecards_data.to_json %>
</div>
<ul class="row" style="list-style:none;">
	<li class="span-md-12"> 
		<div class="portlet solid blue">
			<div class="portlet-title">
				<div class="caption">All Scores</div>
        <div class="actions">Overall Average: <span class="number" id="overall-average"></span></div>
			</div>
			<div class="portlet-body" id="all-criteria-chart">
			</div>
		</div>
	</li>
</ul>
<ul style="list-style:none;" class="row" id="series-charts"></ul>