config/routes.rb
Gradr::Application.routes.draw do
  root 'users#request_invite'
  post '/' => 'users#request_invite', as: 'invite_request'
  get 'login/:slug/:link_hash' => 'users#login'
  get 'logout' => 'users#logout', as: 'logout'
  get 'dashboard' => 'users#dashboard', as: 'dashboard'
  get 'stats/for/:gradee_slug/by/:grader_slug' => 'users#stats', as: 'user_stats'
  get 'scorecard' => 'scorecards#edit', as: 'scorecard_editor'
  post 'scorecard/:id/invite-gradee' => 'scorecards#invite_gradee'
  post 'scorecard/:id/save' => 'scorecards#save'
  post 'criteria/create' => 'criteria#create', as: 'criteria_create'
  post 'criteria/remove' => 'criteria#remove', as: 'criteria_remove'

  

end

app/views/shared/_top_nav.html.erb
   <div class="header navbar navbar-inverse navbar-fixed-top">
      <!-- BEGIN TOP NAVIGATION BAR -->
      <div class="header-inner">
         <!-- BEGIN LOGO -->  
         <a class="navbar-brand" href="/">
          <h2 style="margin-top:-12px;">GRADR</h2>
         </a>
         <!-- END LOGO -->
         <% if !defined?(compact) || !compact %>
         <!-- BEGIN RESPONSIVE MENU TOGGLER --> 
         <a href="javascript:;" class="navbar-toggle" data-toggle="collapse" data-target=".navbar-collapse">
         <img src="/assets/img/menu-toggler.png" alt="" />
         </a> 
         <!-- END RESPONSIVE MENU TOGGLER -->
         <!-- BEGIN TOP NAVIGATION MENU -->
         <ul class="nav navbar-nav pull-right">
            <!-- BEGIN USER LOGIN DROPDOWN -->
            <li class="dropdown user">
               <a href="#" class="dropdown-toggle" data-toggle="dropdown" data-hover="dropdown" data-close-others="true">
               <img alt="" src="<%= current_user.gravatar_url %>?s=30"/>
               <span class="username"><%= current_user.email %></span>
               <i class="icon-angle-down"></i>
               </a>
               <ul class="dropdown-menu">
                  <li>
                    <a href="<%= url_for logout_url %>">
                      <i class="icon-key"></i> Log Out
                    </a>
                  </li>
               </ul>
            </li>
            <!-- END USER LOGIN DROPDOWN -->
         </ul>
         <!-- END TOP NAVIGATION MENU -->
         <% end %>
      </div>
      <!-- END TOP NAVIGATION BAR -->
   </div>
   <!-- END HEADER -->